name: rws-upar-challenge
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - pytorch>=2.2
  - torchvision>=0.17
  - pillow
  - typing_extensions
  - tqdm
  - notebook
  - gdown
  - requests
  - numpy
  - pip
  - pip:
      - open_clip_torch>=2.26,<3
